POST http://localhost:5000/api/register
Authorization: Bearer (my-access-token)
Content-Type: application/json

{
  "fullname": "Jukka Mono",
  "username": "Jukka",
  "email": "jukka@mono.com",
  "password": "securepassword",
  "gender": "male"
}